<a href="https://colab.research.google.com/github/manjunath1005/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

In [12]:
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [9]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
arr_3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
ones=np.ones((2,7))
print(ones)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [14]:
random_arr=np.random.random((2,2))
print(random_arr)

[[0.02617084 0.05940606]
 [0.71953125 0.45336358]]


In [15]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [20]:
arr=np.linspace(1,5,9)
print(arr)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [19]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("Size:",arr.size)
print("Shape:",arr.shape)
print("Data Type:",arr.dtype)
print("Number of dimensions:",arr.ndim)

[[1 2 3]
 [4 5 6]]
Size: 6
Shape: (2, 3)
Data Type: int64
Number of dimensions: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity

In [27]:
temp_data=np.array([[30,28,20],[32,35,27]])
print(temp_data)
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data Type:",temp_data.dtype)
print("Dimensions:",temp_data.ndim)

[[30 28 20]
 [32 35 27]]
Shape: (2, 3)
Size: 6
Data Type: int64
Dimensions: 2


In [32]:
third_greenhouse=np.array([[21,23,22]])
updated_temp_data=np.append(temp_data,third_greenhouse,axis=0)
print(updated_temp_data)

[[30 28 20]
 [32 35 27]
 [21 23 22]]


In [41]:
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)
greenhouse_identity=np.eye(3)
print(greenhouse_identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
print("Updated_temp_data:\n",updated_temp_data)
print("Sensor_error_flag:\n",sensor_error_flags)
print("greenhouse_identity:\n",greenhouse_identity)

Updated_temp_data:
 [[30 28 20]
 [32 35 27]
 [21 23 22]]
Sensor_error_flag:
 [[0. 0. 0.]
 [0. 0. 0.]]
greenhouse_identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [55]:
shipments=np.array([[200,300,150,400,200,80,600],[100,150,130,200,250,200,150]])

In [56]:
print("No.of Apples Shipped on Wednesday:",shipments[0][2])
print("No.of Oranges Shipped on Sunday:",shipments[1][6])

No.of Apples Shipped on Wednesday: 150
No.of Oranges Shipped on Sunday: 150


In [57]:
print("weekday shipments (Mon–Fri) for all fruits:\nApples:",shipments[0][:5],"\nOranges:",shipments[1][:5])
print("Weekend Shipments(Sat & Sun):\nApples:",shipments[0][5:7],"\nOranges:",shipments[1][5:7])
print("shipments of Apples from Wednesday to Saturday:",shipments[0][3:6])

weekday shipments (Mon–Fri) for all fruits:
Apples: [200 300 150 400 200] 
Oranges: [100 150 130 200 250]
Weekend Shipments(Sat & Sun):
Apples: [ 80 600] 
Oranges: [200 150]
shipments of Apples from Wednesday to Saturday: [400 200  80]


In [59]:
shipments[0][5]=100
print("Updated Details of Apples Shipment on Sat:",shipments[0,5])

Updated Details of Apples Shipment on Sat: 100


Array operations


In [65]:
#arithmetic
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a*b)
print(a*2)
print(np.dot(a,b))

#matrixMultiplication
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result=np.dot(mat1,mat2)
print(result)

[5 7 9]
[ 4 10 18]
[2 4 6]
32
[[19 22]
 [43 50]]


Broadcasting

In [64]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


Universal Functions


In [69]:
x=np.array([1,2,3])
y=np.array([4,5,6])
#1. Arithmetic ufuncs
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]


In [70]:
#2. Exponential and Logarithmic ufuncs
print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.log2(x))
print(np.expm1(x))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[ 1.71828183  6.3890561  19.08553692]


In [188]:
#3. Trigonometric ufuncs
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))

0.1411200080598672
-0.9899924966004454
-0.1425465430742778
1.2490457723982544
171.88733853924697
0.05235987755982989


In [72]:
#4. Rounding ufuncs

print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [73]:
#5. Statistical ufuncs (Operate along an axis or entire array)
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))

1
3
2.0
0.816496580927726
0.6666666666666666
6
6


In [74]:
#6. Logical ufuncs
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x,y))

[ True  True  True]
[ True  True  True]
[False False False]
[False False False]


In [75]:
#7. Comparison ufuncs (Return Boolean arrays)
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))

[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


In [76]:
x=3
y=2
#8. Bitwise ufuncs (Operate on integers)
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.invert(x))

2
3
1
-4


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [112]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC],dtype=float)
print(production_all)
print("Shape:",production_all.shape)
print("Size:",production_all.size)
print("Data Type:",production_all.dtype)
print("Dimensions:",production_all.ndim)

[[[10. 12. 11.]
  [ 9. 11. 10.]
  [12. 13. 14.]
  [ 8.  7.  9.]]

 [[20. 19. 21.]
  [18. 20. 19.]
  [22. 23. 21.]
  [17. 18. 16.]]

 [[15. 16. 14.]
  [14. 13. 15.]
  [16. 17. 18.]
  [12. 11. 13.]]]
Shape: (3, 4, 3)
Size: 36
Data Type: float64
Dimensions: 3


In [106]:
total_per_farm=np.array([np.sum(farmA),np.sum(farmB),np.sum(farmC)])
print("Total Energy Per Farm:",total_per_farm)
mean_per_farm=np.array([np.mean(farmA),np.mean(farmB),np.mean(farmC)])
print("Total mean Per Farm:",mean_per_farm)
std_per_farm=np.array([np.std(farmA),np.std(farmB),np.std(farmC)])
print("Total Standard Deviation Per Farm:",std_per_farm)
var_per_farm=np.array([np.var(farmA),np.var(farmB),np.var(farmC)])
print("Total Variance Per Farm:",var_per_farm)

Total Energy Per Farm: [126 234 174]
Total mean Per Farm: [10.5 19.5 14.5]
Total Standard Deviation Per Farm: [1.97905701 1.97905701 1.97905701]
Total Variance Per Farm: [3.91666667 3.91666667 3.91666667]


In [104]:
hour_weights=np.array([0.5,1.0,0.75])
print("weighted_per_panel of FarmA",np.dot(farmA,hour_weights))
print("weighted_per_panel of FarmB",np.dot(farmB,hour_weights))
print("weighted_per_panel of FarmC",np.dot(farmC,hour_weights))

weighted_per_panel of FarmA [25.25 23.   29.5  17.75]
weighted_per_panel of FarmB [44.75 43.25 49.75 38.5 ]
weighted_per_panel of FarmC [34.   31.25 38.5  26.75]


In [113]:
#fixed calibration offset
production_all[1]=production_all[1]+0.5
print(production_all)

[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]


In [114]:
# Reshape mean and std for broadcasting along panels and hours
mean_reshaped = mean_per_farm[:, None, None]  # shape (3,1,1)
std_reshaped = std_per_farm[:, None, None]    # shape (3,1,1)

normalized = (production_all - mean_reshaped) / std_reshaped
print("Normalized Data:\n", normalized)


Normalized Data:
 [[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 0.50529115  0.          1.01058231]
  [-0.50529115  0.50529115  0.        ]
  [ 1.51587346  2.02116461  1.01058231]
  [-1.01058231 -0.50529115 -1.51587346]]

 [[ 0.25264558  0.75793673 -0.25264558]
  [-0.25264558 -0.75793673  0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]]


In [117]:
#  Exponential family ufuncs
exp_normalized = np.exp(normalized)
expm1_normalized = np.expm1(normalized)

# To safely apply logs, shift normalized data to positive range:
log_input = normalized + 5  # shift by +5 to avoid log of <=0
log_normalized = np.log(log_input)
log10_normalized = np.log10(log_input)
log2_normalized = np.log2(log_input)

print("exp_normalized shape:", exp_normalized.shape, "first row farm0 panel0:", exp_normalized[0,0])
print("log_normalized shape:", log_normalized.shape, "first row farm0 panel0:", log_normalized[0,0])

#  Trigonometric ufuncs
sin_normalized = np.sin(normalized)
cos_normalized = np.cos(normalized)
tan_normalized = np.tan(normalized)

# arcsin and arccos require inputs in [-1, 1], so clip:
clipped = np.clip(normalized, -1, 1)
arcsin_normalized = np.arcsin(clipped)
arccos_normalized = np.arccos(clipped)
arctan_normalized = np.arctan(normalized)

# Convert radians to degrees and vice versa (use normalized as degrees input):
degrees_normalized = np.degrees(normalized)
radians_normalized = np.radians(normalized)

print("sin_normalized first row:", sin_normalized[0,0])
print("arcsin_normalized first row:", arcsin_normalized[0,0])
print("degrees_normalized first row:", degrees_normalized[0,0])

#  Rounding ufuncs
round_normalized = np.round(normalized)
floor_normalized = np.floor(normalized)
ceil_normalized = np.ceil(normalized)
trunc_normalized = np.trunc(normalized)

print("round_normalized first row:", round_normalized[0,0])
print("floor_normalized first row:", floor_normalized[0,0])

#  Comparison & logical ufuncs
high_output = production_all > 20

# even_hours_mask shape (3,), broadcast over hours dimension (axis=2)
even_hours_mask = np.array([True, False, True])
even_hours_mask_3d = even_hours_mask[None, None, :]  # shape (1,1,3) broadcast

high_and_even = np.logical_and(high_output, even_hours_mask_3d)
high_or_even = np.logical_or(high_output, even_hours_mask_3d)
not_high = np.logical_not(high_output)
high_xor_even = np.logical_xor(high_output, even_hours_mask_3d)

print("high_and_even example farm 1:\n", high_and_even[1])

# Comparison ufunc examples:
greater_equal_20 = np.greater_equal(production_all, 20)
less_15 = np.less(production_all, 15)
print("greater_equal_20 shape:", greater_equal_20.shape)

#  Bitwise ufuncs on integer arrays
alerts = np.array([[1,0,1],
                   [0,0,1],
                   [1,1,0],
                   [0,1,0]])

# Repeat for 3 farms → shape (3,4,3)
alerts_all = np.tile(alerts, (3,1,1))

bitwise_and = np.bitwise_and(alerts_all, 1)  # just identity here
bitwise_or = np.bitwise_or(alerts_all, 1)    # all ones
bitwise_invert = np.bitwise_not(alerts_all) # invert bits

print("bitwise_and farm 0:\n", bitwise_and[0])
print("bitwise_invert farm 0:\n", bitwise_invert[0])

#  Arithmetic ufuncs again on normalized
added = np.add(normalized, 2)
subtracted = np.subtract(normalized, 1)
multiplied = np.multiply(normalized, 3)
divided = np.divide(normalized, 2)
powered = np.power(normalized, 2)
modulus = np.mod(normalized, 1)  # fractional part

print("added first row:", added[0,0])

#  Aggregations over ufunc outputs
sum_exp = np.sum(exp_normalized)
mean_sin = np.mean(sin_normalized)

print("Sum of exp_normalized:", sum_exp)
print("Mean of sin_normalized:", mean_sin)


exp_normalized shape: (3, 4, 3) first row farm0 panel0: [0.77674313 2.13386893 1.2874269 ]
log_normalized shape: (3, 4, 3) first row farm0 panel0: [1.5575875  1.7505792  1.65873187]
sin_normalized first row: [-0.24996642  0.68742445  0.24996642]
arcsin_normalized first row: [-0.25541356  0.86014434  0.25541356]
degrees_normalized first row: [-14.47552524  43.42657571  14.47552524]
round_normalized first row: [-0.  1.  0.]
floor_normalized first row: [-1.  0.  0.]
high_and_even example farm 1:
 [[ True False  True]
 [False False False]
 [ True False  True]
 [False False False]]
greater_equal_20 shape: (3, 4, 3)
bitwise_and farm 0:
 [[1 0 1]
 [0 0 1]
 [1 1 0]
 [0 1 0]]
bitwise_invert farm 0:
 [[-2 -1 -2]
 [-1 -1 -2]
 [-2 -2 -1]
 [-1 -2 -1]]
added first row: [1.74735442 2.75793673 2.25264558]
Sum of exp_normalized: 63.071430863729034
Mean of sin_normalized: 0.04853967380227196


In [116]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


Stacking and Splitting

In [121]:
a=np.array([[1,2,3],[8,9,0]])
b=np.array([[4,5,6],[12,11,10]])

#vertical stack
print(np.vstack((a,b)))

#horizontal stack
print(np.hstack((a,b)))

#splitting
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[[ 1  2  3]
 [ 8  9  0]
 [ 4  5  6]
 [12 11 10]]
[[ 1  2  3  4  5  6]
 [ 8  9  0 12 11 10]]
[array([1, 2]), array([3, 4]), array([5, 6])]


Advanced Indexing


In [124]:
#a.Boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

#b.fancy indexing
indices=[0,2]
print(arr[indices])

[4 5]
[1 3]


Copy vs View

In [126]:
#View shares memory (shallow copy)
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)

#copy does not share memory (deep copy)
copy=arr.copy()
copy[0]=11
print(arr)

[10  2  3]
[10  2  3]


Saving and Loading

In [129]:
#a.Save to a file
arr=np.array([1,2,3])
np.save("array.npy",arr)

#Load from a file
loaded_arr=np.load("array.npy")
print(loaded_arr)

[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [131]:
arr_1d=np.arange(10,51)
arr_random=np.random.random((3,3))
print(arr_1d,arr_random,sep="\n")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.23217761 0.54487586 0.85589625]
 [0.42201201 0.65803271 0.93426482]
 [0.0997678  0.46818733 0.19848825]]


In [132]:
print("Shape of arr_1d:",arr_1d.shape)
print("Size of arr_1d:",arr_1d.size)
print("Data Type of arr_1d:",arr_1d.dtype)
print("Shape of arr_random:",arr_random.shape)
print("Size of arr_random:",arr_random.size)
print("Data Type of arr_random:",arr_random.dtype)

Shape of arr_1d: (41,)
Size of arr_1d: 41
Data Type of arr_1d: int64
Shape of arr_random: (3, 3)
Size of arr_random: 9
Data Type of arr_random: float64


In [135]:
updated_arr_1d=np.add(arr_1d,5)
print(updated_arr_1d)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
ele_wise_mul=np.multiply(arr1,arr2)
print(ele_wise_mul)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 7 16 27]
 [40 55 72]]


In [155]:
arr_5d=np.array(np.arange(1,26)).reshape(5,5)
print(arr_5d)
print("First row:",arr_5d[0,])
print("Last Column:",arr_5d[:,-1])
print("subarray of the first three rows and first two columns:\n",arr_5d[0:3,0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
subarray of the first three rows and first two columns: [[ 1  2]
 [ 6  7]
 [11 12]]


In [157]:
arr_10=np.random.randint(10,101,10)
print("Maximum Value:",np.max(arr_10))
print("Minimum Value:",np.min(arr_10))
print("Mean and Std:",np.mean(arr_10)," ",np.std(arr_10))

Maximum Value: 91
Minimum Value: 25
Mean and Std: 55.0   25.51078203426935


In [158]:
arr=np.arange(1,13)
reshaped_arr=arr.reshape(3,4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [161]:
arr_ones=np.ones((3,3))
arr=np.array([1,2,3])
arr=np.add(arr_ones,arr)
print(arr)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [168]:
arr=np.random.randint(1,51,10)
print(arr[arr%5==0])

[30 15 50 40]


In [170]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12],[13,14,15]])
arr3=np.dot(arr1,arr2)
print(arr3)

[[ 66  72  78]
 [156 171 186]]


In [187]:
arr_4d=np.random.randint(1,25,16).reshape(4,4)
print(arr_4d)
indices=[0,1,2,3]
print("Diagonal Elements:",arr_4d[indices,indices])

[[21 21  7 15]
 [ 2 20 18 14]
 [11 13  4  7]
 [15  2 10 22]]
Diagonal Elements: [21 20  4 22]
